CREATE TABLE `site_settings` (
	`id` int NOT NULL DEFAULT 1,
	`siteName` varchar(80) NOT NULL,
	`siteSubtitle` varchar(120) NOT NULL,
	`avatarSrc` varchar(500) NOT NULL,
	`avatarAlt` varchar(255) NOT NULL,
	`authorName` varchar(100) NOT NULL,
	`authorLabel` varchar(120) NOT NULL,
	`authorIntroduction` text NOT NULL,
	`authorInterests` text NOT NULL,
	`statusLabel` varchar(80) NOT NULL,
	`statusText` text NOT NULL,
	`statusUpdatedLabel` varchar(80) NOT NULL,
	`githubLabel` varchar(40) NOT NULL,
	`githubHandle` varchar(120) NOT NULL,
	`githubHref` varchar(500) NOT NULL,
	`emailLabel` varchar(40) NOT NULL,
	`emailAddress` varchar(320) NOT NULL,
	`emailHref` varchar(500) NOT NULL,
	`homeOpeningTitle` text NOT NULL,
	`homeOpeningDescription` text NOT NULL,
	`quoteFallback` varchar(500) NOT NULL,
	`featuredPostIds` text NOT NULL,
	`backgroundWhitelist` text NOT NULL,
	`navigationOrder` text NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `site_settings_id` PRIMARY KEY(`id`)
);
