import { useRoute, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUpRight, Image as ImageIcon } from "lucide-react";

export default function GalleryDetail() {
  const [, params] = useRoute("/gallery/:id");
  const [, navigate] = useLocation();
  const galleryId = Number(params?.id || 0);
  const { data: gallery, isLoading, error } = trpc.galleries.getById.useQuery({ id: galleryId }, { enabled: galleryId > 0, retry: false });
  if (isLoading) return <div className="grid min-h-[55vh] place-items-center"><p className="text-sm text-slate-300">正在打开图片集…</p></div>;
  if (error || !gallery) return <div className="grid min-h-[55vh] place-items-center px-4 text-center"><div className="rounded-3xl border border-white/[0.14] bg-[#222832]/78 px-7 py-10 shadow-xl shadow-black/10"><p className="text-sm text-slate-300">这个图片集暂时无法查看</p><h1 className="display-title mt-4 text-4xl">链接可能已失效，<br />或内容尚未公开。</h1><p className="mt-4 text-sm text-slate-400">可以返回列表，查看其他已公开的图片集。</p><button onClick={() => navigate("/gallery")} className="editorial-button mt-7 px-5">返回图片集列表</button></div></div>;
  return <div className="pb-10"><button onClick={() => navigate("/gallery")} className="mb-6 flex items-center gap-2 rounded-lg px-2 py-2 text-sm text-slate-300 hover:bg-white/[0.08] hover:text-[#bce8eb]"><ArrowLeft size={15} /> 返回图片集列表</button><section className="grid overflow-hidden rounded-[1.6rem] border border-white/[0.14] bg-[#202630]/78 px-6 py-10 shadow-xl shadow-black/10 sm:px-10 sm:py-14 lg:grid-cols-12"><div className="lg:col-span-7"><p className="text-sm text-slate-300">图片集</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">{gallery.title}</h1></div><div className="mt-7 max-w-md lg:col-span-4 lg:col-start-9 lg:mt-2"><p className="copy-lede">{gallery.description || "这个图片集暂未填写说明。"}</p><p className="mt-5 text-sm text-slate-300">{gallery.images.length} 张图片 · 创建于 {new Date(gallery.createdAt).toLocaleDateString("zh-CN")}</p></div></section>{gallery.images.length ? <section className="columns-1 gap-4 py-6 sm:columns-2 lg:columns-3">{gallery.images.map((image: any, index: number) => <figure key={image.id} className="mb-4 break-inside-avoid overflow-hidden rounded-2xl border border-white/[0.12] bg-[#202630]/64 shadow-lg shadow-black/10"><img src={image.url} alt={image.title || `${gallery.title} 图片 ${index + 1}`} loading="lazy" className="block h-auto w-full" /><figcaption className="flex items-start justify-between gap-4 p-4"><div><p className="text-xs text-slate-400">图片 {index + 1}</p>{image.title && <p className="mt-1 text-sm font-medium text-slate-100">{image.title}</p>}{image.description && <p className="mt-1 text-sm leading-6 text-slate-300">{image.description}</p>}</div><a href={image.url} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-slate-300 hover:bg-white/[0.08] hover:text-[#bce8eb]" aria-label="在新窗口打开原图"><ArrowUpRight size={16} /></a></figcaption></figure>)}</section> : <section className="mt-6 grid min-h-80 place-items-center rounded-2xl border border-dashed border-white/[0.16] bg-[#202630]/52 px-5 text-center"><div><ImageIcon size={24} className="mx-auto text-slate-400" /><p className="mt-5 text-sm font-medium text-slate-200">这个图片集还没有公开图片</p><p className="mt-3 text-sm text-slate-400">管理员上传图片后，图片会显示在这里。</p></div></section>}</div>;
}
