import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { ArrowRight, ArrowUpRight, BookOpen, Clock3, Eye, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { formatReadingTime } from "@/lib/readingTime";
import { splitHomePosts } from "@/lib/homePosts";
import { formatHomeQuote } from "@/lib/homeQuote";
import { resolveSiteSettings } from "@/lib/siteSettings";
import { AuthorIdentityCard } from "@/components/AuthorIdentityCard";

const observatoryCover = "/manus-storage/observatory-night_fc4b375d.jpg";

function coverFor(post: any) { return post?.coverImage || observatoryCover; }
function formatDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString("zh-CN", { month: "long", day: "numeric" }) : "尚未发布"; }

export default function Home() {
  const [, navigate] = useLocation();
  const { data: posts, isLoading } = trpc.posts.list.useQuery({ page: 1, limit: 5 });
  const { data: persistedSettings } = trpc.site.settings.useQuery(undefined, { staleTime: 1000 * 60 * 5 });
  const siteSettings = resolveSiteSettings(persistedSettings);
  const { featured: newestPost, latest } = splitHomePosts<any>(posts?.data ?? []);
  const { data: quote, isFetching: isQuoteFetching, refetch: refetchQuote } = trpc.quote.current.useQuery(undefined, { staleTime: 1000 * 60 * 30, refetchOnWindowFocus: false });

  return <div className="pb-12">
    <section className="grid gap-8 border-b border-white/[0.28] pb-10 pt-4 sm:gap-12 sm:pb-16 sm:pt-10 lg:grid-cols-[minmax(0,1.05fr)_minmax(18rem,0.95fr)] lg:items-stretch" aria-label="作者介绍与此刻一言">
      <AuthorIdentityCard className="min-h-[18rem] lg:h-full" />
      <aside className="relative flex min-h-[18rem] flex-col justify-between overflow-hidden rounded-[1.35rem] border border-[#d0f4ee]/25 bg-[#40515c]/58 p-6 shadow-[0_20px_46px_rgb(10_18_24_/_18%)] backdrop-blur-md sm:p-8" aria-label="此刻一言"><div className="pointer-events-none absolute -right-12 -top-12 h-44 w-44 rounded-full border border-[#d0f4ee]/15" /><div><p className="editorial-kicker text-[#d0f4ee]">此刻一言</p><p className="mt-7 font-serif text-2xl leading-relaxed text-[#fff8ed] sm:text-3xl" aria-live="polite">{formatHomeQuote(quote?.text || siteSettings.quoteFallback)}</p></div><div className="mt-8 flex flex-wrap items-end justify-between gap-4 border-t border-white/[0.18] pt-4"><div className="text-xs text-[#d0cfca]"><p className="font-mono tracking-[0.1em] text-[#d6fbfc]">PUBLIC QUOTE</p>{quote?.source && <p className="mt-1">— {quote.source}</p>}</div><button type="button" onClick={() => void refetchQuote()} disabled={isQuoteFetching} className="inline-flex items-center gap-1.5 rounded-full border border-white/[0.24] px-3 py-2 text-xs text-[#e5e2db] transition-colors hover:border-[#d0f4ee] hover:text-[#d0f4ee] disabled:cursor-wait disabled:opacity-60" aria-label="从公开一言接口换一句"><RefreshCw size={13} className={isQuoteFetching ? "animate-spin" : ""} />{isQuoteFetching ? "更新中" : "换一句"}</button></div></aside>
    </section>

    <section className="mt-10 border-b border-white/[0.22] pb-10 sm:mt-14 sm:pb-14" aria-labelledby="home-introduction-heading">
      <div className="flex min-w-0 flex-col justify-between border-l border-[#eab78c] pl-5 sm:pl-8">
        <div><p className="editorial-kicker">从经验里留下可复用的线索</p><h1 id="home-introduction-heading" className="display-title mt-5 max-w-5xl whitespace-pre-line text-4xl leading-[1.04] sm:text-6xl">{siteSettings.home.openingTitle}</h1><p className="copy-lede mt-6 max-w-3xl text-[#e5e2db] sm:text-lg">{siteSettings.home.openingDescription}</p><div className="mt-6 flex flex-wrap gap-2" aria-label="阅读主题">{siteSettings.author.interests.map((interest) => <span key={interest} className="rounded-full border border-white/[0.24] px-3 py-1.5 font-mono text-[10px] tracking-[0.06em] text-[#d6fbfc]">{interest}</span>)}</div></div>
        <div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => navigate("/posts")} className="editorial-button editorial-button-primary px-4">从最新记录开始 <ArrowRight size={15} className="ml-2" /></Button><button type="button" onClick={() => navigate("/timeline")} className="editorial-button px-4 text-[#fff8ed]">沿时间阅读 <ArrowUpRight size={14} className="ml-2" /></button></div>
      </div>
    </section>

    <section className="pt-14 sm:pt-20" aria-labelledby="latest-posts-heading"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="editorial-kicker">最近发布 · {String(posts?.total || 0).padStart(2, "0")} 篇公开文章</p><h2 id="latest-posts-heading" className="display-title mt-3 text-4xl sm:text-5xl">最新文章</h2></div><button onClick={() => navigate("/posts")} aria-label="浏览文章列表" className="group flex items-center gap-2 self-start border-b border-white/[0.35] pb-1 text-sm text-[#f4ede3] transition-colors hover:border-[#d0f4ee] hover:text-[#d0f4ee] sm:self-auto">全部文章 <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></button></div>
      {isLoading ? <div className="mt-8 grid animate-pulse overflow-hidden border border-white/[0.18] lg:grid-cols-12"><div className="min-h-[310px] bg-white/[0.06] lg:col-span-5" /><div className="min-h-[310px] bg-white/[0.1] lg:col-span-7" /></div> : newestPost ? <><button type="button" onClick={() => navigate(`/posts/${newestPost.slug}`)} className="group mt-8 grid w-full overflow-hidden border border-white/[0.24] text-left transition-colors hover:border-[#d0f4ee]/70 lg:grid-cols-12" aria-label={`阅读最新文章：${newestPost.title}`}><div className="flex min-h-[320px] flex-col justify-between px-5 py-7 sm:px-8 sm:py-9 lg:col-span-5"><div><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#d0cfca]"><span className="font-mono tracking-[0.1em] text-[#d0f4ee]">刚写下</span><span>{newestPost.category?.name || "未分类"}</span><span>{formatDate(newestPost.publishedAt)}</span></div><h3 className="display-title mt-5 text-3xl leading-tight text-[#fff8ed] transition-colors group-hover:text-[#d0f4ee] sm:text-4xl">{newestPost.title}</h3><p className="mt-5 line-clamp-3 max-w-lg text-sm leading-7 text-[#dfddd7] sm:text-base">{newestPost.excerpt || "这篇记录暂未填写摘要。"}</p></div><div className="mt-8 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#d5d5d0]"><span className="flex items-center gap-1.5"><Clock3 size={13} />{formatReadingTime(newestPost.content || "")}</span><span className="flex items-center gap-1.5"><Eye size={13} />{newestPost.viewCount || 0}</span><span className="flex items-center gap-1.5 text-[#d0f4ee]">阅读全文 <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></span></div></div><div className="article-cover min-h-[255px] lg:col-span-7 lg:min-h-[430px]"><img src={coverFor(newestPost)} alt={newestPost.title} fetchPriority="high" /></div></button>
        {latest.length > 0 ? <div className="mt-8 divide-y divide-white/[0.2] border-y border-white/[0.2]">{latest.map((post: any, index: number) => <button key={post.id} type="button" onClick={() => navigate(`/posts/${post.slug}`)} className="group grid w-full cursor-pointer gap-5 py-5 text-left transition-colors hover:bg-white/[0.055] sm:grid-cols-[auto_minmax(0,1fr)_170px] sm:items-center sm:gap-8 sm:px-4 sm:py-7" aria-label={`阅读文章：${post.title}`}><span className="article-index order-2 sm:order-none">{String(index + 2).padStart(2, "0")}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#d5d5d0]"><span>{post.category?.name || "未分类"}</span><span>{formatDate(post.publishedAt)}</span></div><h3 className="mt-2 text-2xl font-medium leading-snug text-[#fff8ed] transition-colors group-hover:text-[#d0f4ee] sm:text-3xl">{post.title}</h3><p className="mt-2 line-clamp-2 max-w-2xl text-sm leading-7 text-[#dfddd7]">{post.excerpt || "尚未填写摘要。"}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#d5d5d0]"><span className="flex items-center gap-1.5"><Clock3 size={13} />{formatReadingTime(post.content || "")}</span><span className="flex items-center gap-1.5"><Eye size={13} />{post.viewCount || 0}</span><span className="flex items-center gap-1.5 text-[#d0f4ee]">阅读 <BookOpen size={13} /></span></div></div><div className="article-cover order-first aspect-[1.8] sm:order-none sm:aspect-[1.18]"><img src={coverFor(post)} alt={post.title} loading="lazy" /></div></button>)}</div> : <p className="mt-8 border-y border-white/[0.2] py-8 text-sm text-[#d0cfca]">更多公开文章会在这里陆续出现。</p>}</> : <div className="mt-8 border-y border-white/[0.2] py-14 text-center"><p className="editorial-kicker">暂时没有公开文章</p><p className="mt-3 text-[#e5e2db]">下一篇发布后，会从这里开始被看见。</p></div>}
    </section>
    <section className="mt-14 grid border-y border-white/[0.22] sm:mt-20 sm:grid-cols-3" aria-label="继续探索">{[["时间轴", "沿发布日期回看", "/timeline"], ["标签", "按主题筛选", "/tags"], ["图片集", "查看已公开的图像", "/gallery"]].map(([label, copy, href], index) => <button key={href} onClick={() => navigate(href)} className={`group flex items-center justify-between px-1 py-5 text-left transition-colors hover:bg-white/[0.055] sm:px-6 ${index > 0 ? "border-t border-white/[0.16] sm:border-l sm:border-t-0" : ""}`}><span><span className="block text-sm font-medium text-[#fff8ed]">{label}</span><span className="mt-1 block text-xs text-[#d0cfca]">{copy}</span></span><ArrowRight size={15} className="text-[#d0cfca] transition-transform group-hover:translate-x-1 group-hover:text-[#d0f4ee]" /></button>)}</section>
  </div>;
}
