import type { CSSProperties } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Pause, Play } from "lucide-react";
import type { MorroTrack } from "@/lib/musicPlaylist";

type FullMusicPlayerProps = { visible: boolean; transition?: "idle-to-controls" | "controls-to-idle" | "controls-to-full" | "full-to-controls" | null; positionClass: string; style?: CSSProperties; track: MorroTrack; trackIndex: number; playlist: readonly MorroTrack[]; playlistLoaded: boolean; lyric: string; audioPlaying: boolean; audioUnavailable: boolean; currentTime: number; duration: number; formatClock: (value: number) => string; onReturnToControls: () => void; onPrevious: () => void; onNext: () => void; onToggle: () => void; onSeek: (value: number) => void; onSelectTrack: (index: number) => void; };

export function FullMusicPlayer({ visible, transition = null, positionClass, style, track, trackIndex, playlist, playlistLoaded, lyric, audioPlaying, audioUnavailable, currentTime, duration, formatClock, onReturnToControls, onPrevious, onNext, onToggle, onSeek, onSelectTrack }: FullMusicPlayerProps) {
  return <aside style={style} className={`full-music-player fixed z-[61] w-[calc(100vw-1.5rem)] max-w-md rounded-[1.25rem] border border-white/[0.3] bg-[#40515c]/97 p-3 shadow-[0_22px_52px_rgb(17_27_34_/_36%)] backdrop-blur-xl sm:p-4 ${positionClass} ${visible ? "full-music-player--visible" : "full-music-player--hidden"} ${transition ? `full-music-player--${transition}` : ""}`} aria-label="音乐播放器" aria-hidden={!visible}>
    <div className="flex gap-3"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-[1rem] border border-white/[0.24]"><img src={track.coverUrl} alt={`${track.title} 的原始内嵌封面`} className="h-full w-full object-cover" /><span className="absolute left-2 top-2 bg-[#1b2b34]/65 px-1 font-mono text-[10px] tracking-[0.1em] text-white/90">{String(trackIndex + 1).padStart(2, "0")}</span></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium text-[#fff8ed]">{track.title}</p><p className="mt-0.5 text-xs text-[#d0cfca]">{track.artist} · 第 {trackIndex + 1} / {playlist.length} 首</p></div><button onClick={onReturnToControls} className="grid h-8 w-8 shrink-0 place-items-center rounded-full text-[#d0cfca] transition-colors hover:bg-white/[0.08] hover:text-[#d0f4ee]" aria-label="返回二级播放控制"><ChevronDown size={17} /></button></div><p className="mt-3 min-h-5 truncate text-sm text-[#d0f4ee]" aria-live="polite">{audioUnavailable ? "音乐暂时不可用" : lyric || "正在读取歌词…"}</p></div></div>
    <div className="mt-4"><input type="range" min="0" max={duration || 0} step="0.1" value={Math.min(currentTime, duration || 0)} onChange={(event) => onSeek(Number(event.target.value))} className="h-1 w-full cursor-pointer accent-[#d0f4ee]" aria-label="拖动播放进度" disabled={audioUnavailable || duration <= 0} /><div className="mt-1 flex justify-between font-mono text-[10px] text-[#d0cfca]"><span>{formatClock(currentTime)}</span><span>{formatClock(duration)}</span></div></div>
    <div className="mt-3 flex items-center justify-center gap-3"><button onClick={onPrevious} className="grid h-9 w-9 place-items-center rounded-full text-[#e5e2db] transition-colors hover:bg-white/[0.08] hover:text-[#d0f4ee]" aria-label="上一首"><ChevronLeft size={18} /></button><button onClick={onToggle} className="grid h-11 w-11 place-items-center rounded-full bg-[#d0f4ee] text-[#1d2b33] transition-transform active:scale-95" aria-label={audioPlaying ? "暂停音乐" : "播放音乐"} disabled={audioUnavailable}>{audioPlaying ? <Pause size={18} /> : <Play size={18} className="ml-0.5" />}</button><button onClick={onNext} className="grid h-9 w-9 place-items-center rounded-full text-[#e5e2db] transition-colors hover:bg-white/[0.08] hover:text-[#d0f4ee]" aria-label="下一首"><ChevronRight size={18} /></button></div>
    <div className="mt-4 max-h-36 overflow-y-auto border-t border-white/[0.16] pt-2" aria-label="选择歌曲">{playlistLoaded && playlist.map((item, index) => <button key={item.id} onClick={() => onSelectTrack(index)} className={`flex w-full items-center justify-between rounded-lg px-2 py-2 text-left transition-colors ${trackIndex === index ? "bg-[#d0f4ee]/12 text-[#e4fffb]" : "text-[#d9d8d3] hover:bg-white/[0.07]"}`} aria-pressed={trackIndex === index}><span className="flex min-w-0 items-center gap-2"><img src={item.coverUrl} alt="" loading="lazy" decoding="async" className="h-6 w-6 rounded object-cover" /><span className="font-mono text-[10px] text-[#d0cfca]">{String(index + 1).padStart(2, "0")}</span><span className="truncate text-xs">{item.title}</span></span><span className="ml-3 shrink-0 text-[10px] text-[#d0cfca]">{item.artist}</span></button>)}</div>
  </aside>;
}
