import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Loader2, Upload, X } from "lucide-react";

interface ImageUploadProps { onUpload: (url: string) => void; value?: string; maxSize?: number; label?: string; compact?: boolean; }
const supportedTypes = ["image/jpeg", "image/png", "image/webp", "image/gif", "image/avif"] as const;
type SupportedImageType = (typeof supportedTypes)[number];
function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("无法读取图片文件")); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }); }

export default function ImageUpload({ onUpload, value, maxSize = 30, label = "图片文件", compact = false }: ImageUploadProps) {
  const [preview, setPreview] = useState(value || ""); const [error, setError] = useState<string | null>(null); const fileInputRef = useRef<HTMLInputElement>(null); const uploadMutation = trpc.media.uploadImage.useMutation();
  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!supportedTypes.includes(file.type as SupportedImageType)) { setError("仅支持 JPG、PNG、WebP、GIF 或 AVIF 图片。"); return; } if (file.size > maxSize * 1024 * 1024) { setError(`图片不能超过 ${maxSize}MB。`); return; } setError(null); try { const dataUrl = await readAsDataUrl(file); const base64 = dataUrl.split(",")[1]; if (!base64) throw new Error("图片编码失败"); const result = await uploadMutation.mutateAsync({ fileName: file.name, mimeType: file.type as SupportedImageType, base64 }); if (!compact) setPreview(result.url); onUpload(result.url); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "上传失败，请重试。"); } finally { if (fileInputRef.current) fileInputRef.current.value = ""; } };
  const clear = () => { setPreview(""); setError(null); onUpload(""); };
  return <div><input ref={fileInputRef} type="file" accept={supportedTypes.join(",")} onChange={handleFileSelect} className="hidden" />{compact ? <><button type="button" onClick={() => fileInputRef.current?.click()} disabled={uploadMutation.isPending} className="inline-flex h-9 items-center gap-2 rounded-lg border border-white/[0.16] bg-white/[0.035] px-3 text-xs text-slate-200 transition-colors hover:border-[#bce8eb]/55 hover:bg-white/[0.08] hover:text-[#d6fbfc] disabled:opacity-50">{uploadMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}{uploadMutation.isPending ? "正在上传" : "插入图片"}</button>{error && <p className="mt-2 border-l-2 border-[#efaa91] pl-2 text-xs text-[#ffd1c4]">{error}</p>}</> : <><p className="text-sm text-slate-300">{label}</p>{preview ? <div className="mt-3"><div className="article-cover relative aspect-[1.8] overflow-hidden rounded-2xl"><img src={preview} alt="上传图片预览" /><button type="button" onClick={clear} className="absolute right-2 top-2 grid h-9 w-9 place-items-center rounded-lg border border-white/30 bg-[#15191f]/85 text-white hover:border-[#efaa91] hover:text-[#ffd1c4]" aria-label="移除图片"><X size={16} /></button></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-[#d6fbfc]">已保存到站内存储</span><Button type="button" onClick={() => fileInputRef.current?.click()} variant="ghost" className="h-auto rounded-lg px-2 py-1 text-xs text-slate-300 hover:bg-white/[0.08] hover:text-[#d6fbfc]">更换图片</Button></div></div> : <button type="button" onClick={() => fileInputRef.current?.click()} disabled={uploadMutation.isPending} className="mt-3 grid w-full place-items-center rounded-2xl border border-dashed border-white/[0.2] bg-white/[0.025] px-5 py-9 text-center transition-colors hover:border-[#bce8eb]/55 hover:bg-white/[0.055] disabled:cursor-not-allowed disabled:opacity-60"><div>{uploadMutation.isPending ? <Loader2 size={22} className="mx-auto animate-spin text-[#bce8eb]" /> : <Upload size={22} className="mx-auto text-slate-300" />}<p className="mt-3 text-sm text-slate-100">{uploadMutation.isPending ? "正在上传图片…" : "选择图片上传"}</p><p className="mt-1 text-xs text-slate-400">JPG · PNG · WebP · GIF · AVIF，最大 {maxSize}MB</p></div></button>}{error && <p className="mt-3 border-l-2 border-[#efaa91] pl-3 text-xs leading-5 text-[#ffd1c4]">{error}</p>}</>}</div>;
}
